### ISSUE TITLE
Joining query

### ISSUE THREAD

**Issue by jtomek** [adriancarriger/angularfire2-offline#10]
Guys, I love angularfire2-offline. It is so powerful. I would like to incorporate it as the key part of my app. To be able to do so, I am currently facing a problem with joining queries. 

Would somebody have a simple example of how to join data with afo? 

I haven`t been successful finding support in the afo tutorials, as well as I have been trying to apply tutorials how to do it with AF2: for example here: [StackOverflow: Joining Flattened Data](http://stackoverflow.com/questions/38421551/joining-flattened-data) but I fail with the following error message: 

> Type 'Observable<void>' is not assignable to type 'AfoListObservable<any[]>'. Property 'ref' is missing in type 'Observable<void>'.

This is the part of the code that is problematic: 

```
  cars: AfoListObservable<any[]>;
  ...
  ngOnInit(){

  	this.cars = this.afo.database.list("users/1/cars")
  	  	.map((_cars) => {
  	  	  	....
  	  	});
  }

```

I have flattened data, as suggested by firebase, but I struggle putting it together. Right now, my cars database has an ownerKey, but not the details. I would like to retrieve that for my cars list.

Could you please help how to construct a Join Query with AFO?

Thanks,
Jakub

**Comment by adriancarriger** [comment]
Hi @jtomek, I put together a quick example of how to join queries:

- [Demo](https://adriancarriger.github.io/angularfire2-offline/issues/10.1/dist/)
- [Code](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/10.1/src/app/app.component.ts)

It looks like you were on the right track. When you `.map` a `AfoListObservable` with the related merge function, you're actually returning a plain Observable and the Afo write methods such as `push`, `set`, and `remove` are no longer available.

So the important thing is to replace:
```ts
cars: AfoListObservable<any[]>;` 
```
with: 
```ts
cars: Observable<any[]>;
```

**Comment by jtomek** [comment]
Hi @adriancarriger

thank you for your help!

Jakub
