### ISSUE TITLE
npm run ionic:build --aot not working

### ISSUE THREAD

**Issue by ronisaha** [adriancarriger/angularfire2-offline#11]
The AOT build is not working. (Using v2.0.3, v1.4.0)

`npm run ionic:build --aot` 

But its working on dev build or ionic serve.

**Comment by adriancarriger** [comment]
Thanks for the report! I can confirm that AOT is not working for Ionic, but is working for Angular (using the Angular CLI).

With Ionic I get the following:

`Cannot read property 'LocalForageToken' of undefined, resolving symbol
            ANGULARFIRE_OFFLINE_PROVIDER`

I'll take a look at this soon. Any help is greatly appreciated!

**Comment by kleeb** [comment]
update Ionic to 2.3.0 and try `npm run ionic:build --prod`

**Comment by adriancarriger** [comment]
@kleeb I tried 2.3.0 and I'm still getting the same error. I've been super busy, but if you're able to get it working with AOT that would be awesome. Thanks!

**Comment by kleeb** [comment]
I got it working with some minor conf changes.
I am using rollup as bundler, with plenty of custom stuff and custom configs.

The only significant change, was to replace `import * as localforage from 'localforage';` with `import localforage from 'localforage';` in `node_modules/angularfire2-offline/src/localforage.js`

**Comment by danielfnz** [comment]
I have the same error.

Cannot read property 'LocalForageToken' of undefined, resolving symbol ANGULARFIRE_OFFLINE_PROVIDER

Any fix?

**Comment by adriancarriger** [comment]
Thanks @kleeb for your help!

🎉 This is now fixed in AngularFire2 Offline version 3.0.0.

Also, here is an [upgrade tutorial](https://github.com/adriancarriger/angularfire2-offline/blob/master/docs/version-4-upgrade.md)
