### ISSUE TITLE
Pagination Ionic

### ISSUE THREAD

**Issue by gabrieltavaresmelo** [adriancarriger/angularfire2-offline#15]
When I use load more data, the AfoListObservable don't load the next 20 elements.

`
 <ion-list>
   <ion-item *ngFor="let i of items">{{i}}</ion-item>
 </ion-list>

 <ion-infinite-scroll (ionInfinite)="doInfinite($event)">
   <ion-infinite-scroll-content></ion-infinite-scroll-content>
 </ion-infinite-scroll>
`

http://ionicframework.com/docs/v2/api/components/infinite-scroll/InfiniteScroll/

**Comment by adriancarriger** [comment]
Can you show your entire component code?

**Comment by adriancarriger** [comment]
I'm closing this because I haven't heard back in a while. Feel free to reopen if you were not able to solve it. Thanks!
