### ISSUE TITLE
Method $exists() doens't work

### ISSUE THREAD

**Issue by rodrifmed** [adriancarriger/angularfire2-offline#19]
When I try to get the result of $exists(), I get this error:

> FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'e' of undefined
>     at Object.V.Lf [as $exists] (http://localhost:8100/build/main.js:167170:95)
>     at SafeSubscriber._next (http://localhost:8100/build/main.js:86423:49)
>     at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/main.js:19833:16)
>     at SafeSubscriber.next (http://localhost:8100/build/main.js:19782:22)
>     at Subscriber._next (http://localhost:8100/build/main.js:19722:26)
>     at Subscriber.next (http://localhost:8100/build/main.js:19686:18)
>     at DoSubscriber._next (http://localhost:8100/build/main.js:185115:30)
>     at DoSubscriber.Subscriber.next (http://localhost:8100/build/main.js:19686:18)
>     at MapSubscriber._next (http://localhost:8100/build/main.js:40947:26)
>     at MapSubscriber.Subscriber.next (http://localhost:8100/build/main.js:19686:18)
>     at AfoListObservable.Subject.next (http://localhost:8100/build/main.js:28291:25)
>     at AfoListObservable.ReplaySubject.next (http://localhost:8100/build/main.js:69780:31)
>     at SafeSubscriber._next (http://localhost:8100/build/main.js:71553:42)
>     at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/main.js:19833:16)
>     at SafeSubscriber.next (http://localhost:8100/build/main.js:19782:22)
>     at Subscriber._next (http://localhost:8100/build/main.js:19722:26) 

I'm using "angularfire2": "^2.0.0-beta.8" and "angularfire2-offline": "2.0.6" with "ionic-angular": "3.0.1"

thanks,

**Comment by adriancarriger** [comment]
Thanks for reporting this issue! `$exists` should now work correctly as of version 2.0.7

**Comment by rodrifmed** [comment]
Thanks Adrian!

Your wrapper is helping a lot my project! Congratulations!

**Comment by adriancarriger** [comment]
@rodrifmed  Awesome, glad to hear that!
