### ISSUE TITLE
Facing issue after following steps to install this plugin under underexisting angularfire2 project

### ISSUE THREAD

**Issue by chit786** [adriancarriger/angularfire2-offline#2]
Below is the console error I am getting:

Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:8100/build/main.js:54251:47)
    at Reflector.parameters (http://localhost:8100/build/main.js:54462:48)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:8100/build/main.js:33075:156)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:8100/build/main.js:33040:26)
    at http://localhost:8100/build/main.js:33187:41
    at Array.forEach (native)
    at CompileMetadataResolver.getProvidersMetadata (http://localhost:8100/build/main.js:33167:19)
    at http://localhost:8100/build/main.js:32859:71
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8100/build/main.js:32850:44)

package.json dependencies:

 "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@ionic/storage": "1.0.3",
    "@types/lodash": "4.14.43",
    "angular2-moment": "^1.0.0",
    "angularfire2": "^2.0.0-beta.6",
    "angularfire2-offline": "^0.1.1",
    "chart.js": "2.3.0",
    "es6-shim": "0.35.0",
    "firebase": "^3.3.0",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-cache": "^1.1.1",
    "ionic-native": "^2.0.3",
    "ionic2-rating": "0.0.10",
    "ionicons": "^3.0.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.0.0-beta.12",
    "systemjs": "0.19.39",
    "typings": "^1.4.0",
    "whatwg-fetch": "^2.0.1",
    "zone.js"

ionic info ;
Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.2.1 Build version 8C1002

Please advice

**Comment by adriancarriger** [comment]
I found what [looks like the project your using](https://github.com/chit786/CAFFEIOT/tree/feature/chitrang-s_feature) (similar [package.json](https://github.com/chit786/CAFFEIOT/blob/feature/chitrang-s_feature/package.json) on your Github) except it doesn't have the AngularFire2Offline library and I got the same error that you posted here. It sounds like this could be potentially unrelated to this library.

If you can post a link of your project working before installing AngularFire2Offline and your implementation after installing I should be able to help. Thanks!

**Comment by chit786** [comment]
Hi Adrian,

Thanks for reaching out, I found after analysis that the root cause of this was that the angularfire2-offline is compiled using new version of CLI then mine. So updating my CLI, >> npm install solved the issue.

Thank you once again 

Additionally,, I was looking on the similar threads like your library and wanted to achieve offline capability.
Can you please suggest if this library has capabilities to sync the offline updates we do with the list/object observable when we become online?

**Comment by adriancarriger** [comment]
Glad you fixed it!

This library will sync any read-only field after your app goes online again for both list/object observables. 

If you have data you want to push to Firebase from an offline state, then use the regular AngularFire2 library. That library will partially work offline, but unpublished data won't survive a complete refresh (or in Ionic's case the data won't survive if a user force quits the app).

If you would like to see full offline support for publishing data back to Firebase please open an issue on this library with the feature request. Thanks!

**Comment by chit786** [comment]
thanks adrian, I will do so in separate issue. Closing this one.
