### ISSUE TITLE
Update to angularfire2 4.0.0rc0

### ISSUE THREAD

**Issue by rodrifmed** [adriancarriger/angularfire2-offline#21]
Hi Adrian,

Do you have plans to upgrade your lib to work with angularfire2 4.0.0rc0?

My question is because on angularfire2 2.0.0-beta8 I can´t run ionic build android --prod, the build fails.

But on new angularfire2 version, this problem was fix.

Thanks,

**Comment by adriancarriger** [comment]
Hi @rodrifmed I would like this library to work with Angularfire2 4.x and I will be looking into supporting it. Thanks for posting the issue!

I'm wondering if your issue with running `ionic build android --prod` is related to [issue #11](https://github.com/adriancarriger/angularfire2-offline/issues/11)?

**Comment by rodrifmed** [comment]
I didn't have problem with angularfire offline. Only with angularfire2.

I made some changes localy on your lib to run with angular2 4.0.0rc0 and works fine the aot compile!

The change is simply, only change AngularFire to AngularFireDatabase on imports and use af.database to only af.

**Comment by rodrifmed** [comment]
I have to change the index.metadata.json too

**Comment by bergergit** [comment]
+1 for this enhancement. This project looks awesome, and it would be great to see it working with latest version of angularfire2 :)

**Comment by adriancarriger** [comment]
🎉 This is now implemented in AngularFire2 Offline version 3.0.0

Also, here is an [upgrade tutorial](https://github.com/adriancarriger/angularfire2-offline/blob/master/docs/version-4-upgrade.md)

**Comment by bergergit** [comment]
Just implemented the change and it worked perfectly! Both in Android (Ionic) and in Browser. Thanks so much for your effort. This project really improves user experience for any Firebase project. 🥇

**Comment by adriancarriger** [comment]
@bergergit Awesome, glad to hear that!
