### ISSUE TITLE
Problem with uniqueNext generating "circular structure to JSON"

### ISSUE THREAD

**Issue by rodrifmed** [adriancarriger/angularfire2-offline#22]
```
AfoObjectObservable.prototype.uniqueNext = function (newValue) {
        if (JSON.stringify(this.previousValue) !== JSON.stringify(newValue)) {
            this.previousValue = newValue;
            this.next(newValue);
        }
    };
```
My console:

> Handler Error TypeError: Converting circular structure to JSON
>     at JSON.stringify (<anonymous>)
>     at AfoObjectObservable.uniqueNext (afo-object-observable.js:112)
>     at SafeSubscriber._next (database.js:206)
>     at SafeSubscriber.__tryOrUnsub (Subscriber.js:236)
>     at SafeSubscriber.next (Subscriber.js:185)
>     at Subscriber._next (Subscriber.js:125)
>     at Subscriber.next (Subscriber.js:89)
>     at Notification.observe (Notification.js:32)
>     at QueueAction.ObserveOnSubscriber.dispatch (observeOn.js:50)
>     at QueueAction.AsyncAction._execute (AsyncAction.js:111)
>     at QueueAction.execute (QueueAction.js:33)
>     at QueueScheduler.AsyncScheduler.flush (AsyncScheduler.js:36)
>     at QueueAction.schedule (QueueAction.js:27)
>     at QueueScheduler.Scheduler.schedule (Scheduler.js:43)
>     at utils.js:79

**Comment by adriancarriger** [comment]
This should be solved as of version 2.0.9. Please let me know if you still experience the issue, thanks!

**Comment by rodrifmed** [comment]
I tested yesterday and works fine!

**Comment by Ross-Rawlins** [comment]
I am still getting this issue.
