### ISSUE TITLE
Empty value on first request offline

### ISSUE THREAD

**Issue by rodrifmed** [adriancarriger/angularfire2-offline#23]
I'm have problem when call the this.dbOff.database first time, the first value returning on subscribe is a $value null.

I start to debug the lib and I found in the method "setupObject" on file "database.ts" that you are sending first the local value that is null and then send the firebase value.

I made one change to see what happens and the lib seems to be okay besides that.

I changed the ` else {
                    _this.objectCache[key].sub.uniqueNext(cacheValue);
                }` ( row 206)

to

`else if (cacheValue && cacheValue.$exists()){
                    _this.objectCache[key].sub.uniqueNext(cacheValue);
                }`

```
this.localForage.getItem("read/object" + key).then(function (value) {
            if (!_this.objectCache[key].loaded) {
                var cacheValue = unwrap(key.split('/').pop(), value, function () { return value !== null; });
                if (_this.processing.current) {
                    _this.processing.objectCache[key] = cacheValue;
                }
                else if (cacheValue && cacheValue.$exists()){
                    _this.objectCache[key].sub.uniqueNext(cacheValue);
                }
            }
        });
```

What do you think?

**Comment by adriancarriger** [comment]
Thanks @rodrifmed, I have implemented a [similar solution](https://github.com/adriancarriger/angularfire2-offline/commit/1df36fe9b31def51268b5802488f4691f1e5cf35) based on your input, and it should now work in version 2.0.10.

**Comment by rodrifmed** [comment]
Very good! Thank you!
