### ISSUE TITLE
Bug in write list

### ISSUE THREAD

**Issue by ajay-sreeram** [adriancarriger/angularfire2-offline#24]
in write a list [Demo](https://angularfire2-offline.firebaseapp.com/write-list)

I am doing these steps:

1. On wifi and go to [Demo](https://angularfire2-offline.firebaseapp.com/write-list)
2. Click on reset
3. Off wifi, add Apples
4. Refresh page, upto this everything is fine
5. Now, On wifi, the list displayed has lot of duplicates
![screenshot](https://cloud.githubusercontent.com/assets/6972283/25771421/f0b7f966-326d-11e7-8e2e-abb9bcdbb829.png)

Please try to resolve this bug or suggest me if there is any way to solve this problem.

**Comment by adriancarriger** [comment]
I was able to reproduce this issue using the last published demo (not sure at the moment which version that was based on).

I just published a new demo based on the latest release (version 3.0.0) and cannot reproduce the issue using the new version so this appears to be fixed.

Please reopen this issue if you are able to reproduce. Thanks!
