### ISSUE TITLE
Angular Cli Build Aot Compilation Error

### ISSUE THREAD

**Issue by rechenberger** [adriancarriger/angularfire2-offline#25]
When I do `ng build --prod --aot`, the following error occurs:

```
ERROR in /path/to/node_modules/angularfire2-offline/src/localforage.d.ts (3,47): C
annot find name 'LocalForage'.
/path/to/node_modules/angularfire2-offline/src/localforage.d.ts (6,23): Cannot fin
d name 'LocalForage'.
```

It can be fixed by adding `
import * as LocalForage from 'localforage';` to `localforage.d.ts`

**Comment by adriancarriger** [comment]
Hi @rechenberger, thanks for opening an issue! The line you changed was [recently update](https://github.com/adriancarriger/angularfire2-offline/commit/bdc482f760b80e92e0e85ffdcd2665172007f1ef#diff-92232b66978bf41a145a74eedbafe306R11). Maybe the latest release will solve your issue?

I just ran `ng build --prod --aot` using the latest version of AngularFire2 Offline (v4.0.1).

Here are steps to reproduce:

1. `git clone https://github.com/adriancarriger/angularfire2-offline.git`
1. `cd angularfire2-offline/examples/angular-cli`
1. `npm install`
1. `npm run ng build --prod --aot`

- What version of AngularFire2 Offline are you using?
- Also, can you try the steps I took and see if you get a different result?

Thanks! 👍

**Comment by rechenberger** [comment]
Using version 4.0.0 worked for me. I was using 2.0.10 before. Thank you.
