### ISSUE TITLE
v5.0.0 here, v3.0.0 on npmjs

### ISSUE THREAD

**Issue by larssn** [adriancarriger/angularfire2-offline#26]
I assume its a typo. :)

My suggestion is to switch to v4.x, to be in sync with both firebase and AF2.

**Comment by adriancarriger** [comment]
Hi @larssn, thanks for posting! I don't see the `v5.0.0` ..where do you see it?

**Comment by larssn** [comment]
Under releases :)

**Comment by adriancarriger** [comment]
Oh thanks, yeah that's an automated post.. I'll update it soon 👍

**Comment by adriancarriger** [comment]
Thanks for opening this issue! I've updated the changelog and the latest version is now at v4.0.1.
