### ISSUE TITLE
Client doesn't have permission to access the desired data - after Sign Out

### ISSUE THREAD

**Issue by bergergit** [adriancarriger/angularfire2-offline#38]
When I sign up a new user, I also create a record for him in the Database:
```
    constructor(public db: AngularFireOfflineDatabase) {}
    ...
    this.usersRef = this.db.object('/users/' + userId);
    this.usersRef.set({
      email: email
    });
```
My DB rules are like this:
```
"users": {
      "$uid": {
        ".read": "$uid === auth.uid",
        ".write": "$uid === auth.uid"
      }
```
This way, user is allowed to read/write only his own data.

When I sign the user off, I get this error message: **/users/1Q6pIqx1BsaikdF7aw5wjryFW4y1: Client doesn't have permission to access the desired data.**

This is probably because the offline reference is still bound to the /users/ object, and since I have signed off, the security rules are applying

But if I use AngularFire2 directly (instead of AngularOffline), it works without any issues.

I would like to use AngularOffline because it would be nice to let user change his profile without a connection (or even make new posts or anything that requires security for his own reads/writes)

Any help on this? 
At least if I had a direct reference to AngularFire2 Database, I could try to call off() on the reference.
Thanks

**Comment by adriancarriger** [comment]
Hi @bergergit, thanks for posting your issue!

> if I had a direct reference to AngularFire2 Database

Doing this should be easy! Here's an example:

```ts
import { Component } from '@angular/core';
import {
  AngularFireDatabase,
  FirebaseObjectObservable } from 'angularfire2/database';
import {
  AfoObjectObservable,
  AngularFireOfflineDatabase } from 'angularfire2-offline/database';

@Component({
  selector: 'project-name-app',
  template: `
  <h1>{{ (info | async)?.name }}</h1>
  <ul>
    <li *ngFor="let item of items | async">
      {{ item?.name }}
    </li>
  </ul>
  `
})
export class MyApp {
  afInfo: FirebaseObjectObservable<any>;
  afoInfo: AfoObjectObservable<any>;
  constructor(afDatabase: AngularFireDatabase, afoDatabase: AngularFireOfflineDatabase) {
    this.afInfo = afDatabase.object('/info');
    this.afoInfo = afoDatabase.object('/info');
  }
}
```

Let me know if that doesn't solve it. Thanks!

**Comment by bergergit** [comment]
Hi @adriancarriger 
I tried to do as you posted, but issuing off() in the 'online' database reference, doesn't seem to fix this.
Here is my DbService:
```
import { Injectable } from '@angular/core';
import { AfoListObservable, AngularFireOfflineDatabase, AfoObjectObservable } from 'angularfire2-offline/database';
import { AngularFireDatabase, FirebaseListObservable, FirebaseObjectObservable } from 'angularfire2/database';

@Injectable()
export class DbServiceProvider {

  usersRef: AfoObjectObservable<any>;
  onlineUsersRef: FirebaseObjectObservable<any>;

  constructor(public db: AngularFireOfflineDatabase, public dbOnline: AngularFireDatabase) {
    
  }

  closeRefs() {
    this.onlineUsersRef.$ref.off();
  }

  setUser(userId: string, email: string) {
    this.usersRef = this.db.object('/users/' + userId);
    this.onlineUsersRef = this.dbOnline.object('/users/' + userId);
    this.usersRef.set({
      email: email
    }).catch(err => console.log(err, 'You dont have access!'));
  }

}
```
_(notice the `this.onlineUsersRef.$ref.off();`  I'm assuming this is the correct way of doing it)_

I call setUser() right after signing up a new user.
Then I call closeRefs() right before signing him out, from my auth-service.ts:
```
  signOut(): void {
    this.dbService.closeRefs();
    this.afAuth.auth.signOut();
  }
```

I still get the same error.
I can see that the error shows up about half a second after signing out. That probably means something is executing *after* the sign out process.
Thanks

**Comment by adriancarriger** [comment]
From what I understand you don't need or want to allow access to the data after the user signs out. You might benefit from a new (yet not documented) feature (released last Sunday) which is the `reset` method.

You can use it like this:

```ts
constructor(afoDatabase: AngularFireOfflineDatabase) {
  // Warning: this will clear the browser cache
  this.afoDatabase.reset();
}
```

It will clear the browsers cache. This could be bad if the user made offline writes, and then the `reset` method is called, so be careful.

Let me know if that solves your situation with signing out. You might consider updating your `signOut` method to look like this:

```ts
signOut(): void {
    this.afoDatabase.reset();
    this.dbService.closeRefs();
    this.afAuth.auth.signOut();
}
```

**Comment by bergergit** [comment]
@adriancarriger calling reset() in my closeRefs() method worked!

But I think I found the issue in my case.
After several steps on upgrading my Ionic project, my serviceWorker <script>  was commented out in my index.html!
After uncommenting it, the sign out operation now works, even without calling reset().

It's weird because, the set{} operation in my userReference was working. I could see it in my Firebase DB as soon as user signed up with a new account:
```
this.afAuth.auth.createUserWithEmailAndPassword(email, password)
      .then(newUser => {
        this.dbService.setUser(newUser.uid, email);
      });
```
dbService.setUser():
```
    this.usersRef = this.db.object('/users/' + userId);
    this.usersRef.set({
      email: email
    });
```

Any ideas why is that?
And I think you can mark this as closed.

Thanks again

**Comment by bergergit** [comment]
I think I've spoken too soon 
Because of the serviceWorker, I didn't notice I just was serving my previous version of the file... which had the reset() call.
So, to summarize: calling reset() does the job... but it doesn't seem to be the ideal solution when all writes() in the reference have executed.
Tks

**Comment by adriancarriger** [comment]
So, to clarify:

- Does using `reset()` prevent the error message?
- Is using `reset()` not an ideal solution because you want to wait for writes to complete before calling `reset()`?

If yes to those two questions, then you might consider waiting for all write promises to complete before you call `reset()`.

Also, you could pass the burden to the user when they try to logout by telling them that there is unsaved data. You could give the choice to stay logged in until the writes are made, or sign out right away resulting in unsaved data.

**Comment by bergergit** [comment]
Hello Adrian

1. Yes, reset() does prevent the error message
2. reset() is not ideal because this will clean ALL cached objects (including read lists) right? The thing is... I'm caching a list of DB items, which are open to public (and get cached offline by angular-offline). I don't want to loose them if user signs out and later, looses his connection. Logged in or anonymous users will always see the list, even without internet connection (this is the beauty of angular-offline right? :)
3. Very important: there are *no* pending writes when the user signs out. I sign the user in - save his email to the DB, and the process is finished. User is online, he has internet connection, and the write does finish executing - leaving no writes in any pending state. And even though, I get this error.

This problem doesn't happen with regular AngularFire2 object ref. I don't need to manually close the reference to them after user sign out. This is also not a deal breaker. I can use regular AngularFire2 objects. But it's good to have a discussion and talk about possibilities. :)

Maybe one possibility would be to close / reset only that specific reference (e.g.: /users/${userId}). And not all offline DB refs. What do you think?

**Comment by adriancarriger** [comment]
These are really good points, and I'll be thinking of ways to support this use case. Thanks for the info!

**Comment by adriancarriger** [comment]
I added an option to reset a specific reference in version 4.2.0.

Usage: `this.afoDatabase.reset('/groceries')`

This should remove everything from the UI, application memory, and device storage.

Let me know how it works with regards to your use case. Thanks!

**Comment by bergergit** [comment]
That's excellent!
Now I can call reset() on any protected resources, like: this.afoDatabase.reset('/users') or this.afoDatabase.reset('/posts/{userId}') before signing the user out :)
Thanks @adriancarriger

**Comment by adriancarriger** [comment]
@bergergit Great! Sounds like this solved your issue. Feel free to post here again if you come across any related issues while implementing this new feature. Thanks!
