### ISSUE TITLE
Friend System.

### ISSUE THREAD

**Issue by Nebula-Spark** [adriancarriger/angularfire2-offline#39]
I know its not the right place to ask this question but maybe here i can find some solution,
I am just Stucked @ friend system using Angularfire2 especially how to find my friends status whether they online or offline

My Db is like

Profile- 
       MARIO:
          name: mario
           friends: 
                     PRINCE:  true
           status:online

        PRINCE:
            name:prince
            friends: 
                    MARIO : true
            status:offline
 

Now I want to find  profile array to check if my Key exists on their friends objects return all those lists
So i can ngFor those value and view it on the UI 

Using map Operator
let  key  =  MARIO
 this.Online    =   this.af.list('profile').map( USERS => {
      
   const Filter = USERS.filter( PROFILE =>  PROFILE.friends == key) )
    return Filter

} )

this.Online.subscribe( RES => console.log( RES) )

But the problem is The code is not working i know something wrong here , It would be great If any 1 can give me a solution to this ! 
Or I need to Approach it differently ?

**Comment by adriancarriger** [comment]
Hi @Nebula-Spark, does your code run using [AngularFire2](https://github.com/angular/angularfire2/)? If it doesn't work with that, then it probably won't work with this library ([AngularFire2 Offline](https://github.com/adriancarriger/angularfire2-offline))

If it's working, can you post all of that component's code or link to a repo with your code? Thanks! 👍

**Comment by Nebula-Spark** [comment]
@adriancarriger 
sorry for the late reply , was out of town.
Yup it's running on Angularfire2

**Comment by Nebula-Spark** [comment]
@adriancarriger 
sorry for the late reply , was out of town.
Yup it's running on Angularfire2 
I was trying to make a friend system like facebook,

Everything works  expect one
1. Search a Friend  and send  Friend Request  --  Working
2. Accept the request  ---  Working
3. Add The accepted request  In The Friends list -- Working
3. Create a Private Chat node in database for them  -- Working
4. Chat with your friend  -- Working
But
**5. Find Your friend status whether is he Online or offline  --- Not working or I have no idea how to do it !**


The Big problem i am facing now is ..

 I have Two Array of List Tree In Database
 
 First :    users 
 
 Second  :   userFriends


 In the users Array all of the registerd users and their status  wthere they or online or Offline like

 users/MARIO/{
   
   uid:MARIO,
   name:mario,
   email:mario@gmail.com,
   status:online

 }


 in the Second Array  userFriends . It's  a list of friends for the user  example


 userFriends/Prince{

     MARIO:{
      name:mario,
      friend:true,
       uid:MARIO,
       chatroomkey:key1,
      avatar:./assets/images

     },
      Monster:{
       name:Monster,
       friend:true,
       uid:MONSTER,
       chatroomkey:key2,
       avatar:./assets/images

     }
      
    
     
 }


Now i can easily list my using the following code


for example

let key =  Logged user UID

this.myfriends = Angularfire2offline.list(`userFriends/${key}`)

Now i can easily Get the My friend list and show it on the ui 

but i can get only this values like 

name:mario
avatar:./assets/images,
chatroomkey:key1,
status : ??????????


But i dunno how to get his status

I know itz looks like little bit confusing but it would be great if u can help on this !
