### ISSUE TITLE
Error at this.previousValue.sort((a, b) => a.$key - b.$key) in internal-list-observable.ts

### ISSUE THREAD

**Issue by monad98** [adriancarriger/angularfire2-offline#48]
```TypeError: Cannot assign to read only property '1' of object '[object Array]'```

I got a few of this errors at this line: ```this.previousValue.sort((a, b) => a.$key - b.$key);```
I have a few list observables, but only some list has problem. I don't know where this difference happen. I logged those previousValue array as global variable and check property descriptors. 

![screenshot 2017-07-15 00 41 14](https://user-images.githubusercontent.com/6015975/28237607-e24bbb72-68f7-11e7-86b3-201c052d1bc3.png)

Some array's elements are read-only (in this case, temp2 array), error happen when it tries to sort.
Is there anyone who can explain this?

Edit: One thing I found is when using queryObject like query: {orderByChild: 'name', startAt: 'A', endAt: 'Z'}, previous value array is writable and got no error.

**Comment by adriancarriger** [comment]
Hi @monad98, thanks for posting! Can you show a reproducible example that gives the error you're experiencing?
