### ISSUE TITLE
Network Error when using Ionic

### ISSUE THREAD

**Issue by wbhob** [adriancarriger/angularfire2-offline#52]
When I use this module with Ionic, I get this error:

```
GET https://*******.firebaseio.com/.lp?start=t&ser=62360009&cb=2&v=5 net::ERR_INTERNET_DISCONNECTED
```

This occurs when I don't have internet connection on load. Does anyone else have this issue? I am also unable to `push` on a firebase list when offline.

**Comment by adriancarriger** [comment]
Hi @wbhob, thanks for posting! 

## Errors

The `ERR_INTERNET_DISCONNECTED ` error is normal while your app is offline. The [Afo demo](https://angularfire2-offline.firebaseapp.com/write-list) displays the same behavior. It would be awesome to get rid of the errors, but as far as I know removing the errors would require touching Firebase code (please let me know if this is possible).

## Offline writes

You should be able to push to your angularfire2-offline list while offline. These pushes would only be reflected in your app, and they won't show up in other places such as the Firebase console or other apps that use the same Firebase database until the app in question goes back online. Feel free to test this with [the demo](https://angularfire2-offline.firebaseapp.com/write-list). 👍

## Questions

To help narrow down the issue, please answer these questions:
* Are you unable to push to a list while offline using the demo?
* Are you unable to push to a list while offline using your app?

Thanks!

**Comment by wbhob** [comment]
So I think what happens is that the promises from `push` on lists and `update` on objects aren't being fired if you're offline, a functionality that my app depends on to make sure the data is saved before advancing to the next view.

Should I just move resolution code outside of the promise context for the time being?

**Comment by adriancarriger** [comment]
Turns out that an "offline write promises" feature [is requested](https://github.com/adriancarriger/angularfire2-offline/issues/44#issuecomment-310369220) in issue #44. Would that solve your issue?

**Comment by wbhob** [comment]
It definitely would!

**Comment by adriancarriger** [comment]
Offline writes now work in version 4.2.1!  🎉 

[Demo](https://adriancarriger.github.io/angularfire2-offline/issues/44.2/dist/) (with [Code](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/44.2/src/app/app.component.ts#L29-L31))

## Usage

```ts
const promise = this.afoDatabase.object('car').update({maxSpeed: 100});
promise.offline.then(() => console.log('offline write complete!'));
```

**Comment by wbhob** [comment]
Incredible, thanks so so much!
