### ISSUE TITLE
Managing offline resource usage

### ISSUE THREAD

**Issue by pscott-au** [adriancarriger/angularfire2-offline#56]
I am wondering how to manage the storage usage. I am using in an ionic mobile app ( iOS ) and am concerned that if I am accessing a lot of data that I should be managing or at least keeping an eye on the resource usage. Could we add a couple of lines into the docs to describe how this could be done and any advice on how this works,

**Comment by adriancarriger** [comment]
Hi @pscott-au, right now Afo will store all data from all references used.

Here are some ways to manage that:

* If you no longer need Afo to keep specific data on the device you can call the [`reset`](https://github.com/adriancarriger/angularfire2-offline#reset---delete-offline-data) method on the reference.
* If you have a reference that you don't want stored on the device you can just use AngularFire2 for that specific reference.

Do these options work well for your use case?

**Comment by pscott-au** [comment]
Thanks @adriancarriger 

Would I be correct to assume that if I wish to flush the local storage of a tree that I can call a reset from a subsequently subscribed parent in the tree or do I need to specifically reset the specific record set. 
eg.
If I have an application that loads invoices into an Afo property that is in the FB hierarchy /invoices/$uid/$invoice_id would instantiating an Afo object of /invoices/$uid and calling a `reset` flush out all of the children stored locally?

**Comment by adriancarriger** [comment]
Hi @pscott-au, that's a great question!

* With the [current implementation](https://github.com/adriancarriger/angularfire2-offline/blob/master/src/database/database.ts#L218-L248) for reseting a specific reference it looks like you will need to call `reset` on each reference used in your app (which might require data denormalization)
* Also, calling `reset` with no reference argument will remove all local data from the entire app

If either of these options don't work well for your use case, then feel free to request an enhancement. Thanks! 👍

**Comment by pscott-au** [comment]
For me I find that doing a reset without params on logout seems to do the trick. Cheers.

**Comment by adriancarriger** [comment]
Awesome!
