### ISSUE TITLE
add token to calls

### ISSUE THREAD

**Issue by Ross-Rawlins** [adriancarriger/angularfire2-offline#59]
How can I add my auth token to the calls?

**Comment by adriancarriger** [comment]
It sounds like you're using Firebase auth?

It should work as expected if you just use the regular [AngularFire2 auth methods](https://github.com/angular/angularfire2/blob/master/docs/5-user-authentication.md).

## Related issues

This might be related to #12 and possibly #43

## Code

If you're still having issues would you be able to post the code you're using? Thanks! 👍

**Comment by Ross-Rawlins** [comment]
Angular fire did it all for me thank you.
