### ISSUE TITLE
Cannot find module 'angularfire2/interfaces' 

### ISSUE THREAD

**Issue by netomarchiori** [adriancarriger/angularfire2-offline#62]
Hello, when i try to run the "ionic" example, i get:

```
typescript: node_modules/angularfire2-offline/database/database.d.ts, line: 2
Cannot find module 'angularfire2/interfaces'.

L2:  import { FirebaseListFactoryOpts, FirebaseObjectFactoryOpts } from 'angularfire2/interfaces';
```

For some reason, FirebaseListFactoryOpts is located at 'angularfire2/database/interfaces' not on 'angular/interfaces'

Im using:
angularfire2@4.0.0-rc.2
angularfire2-offline@4.1.1

I manage to fix the code by correcting the imports, however i don't know how to do a pull request

**Comment by adriancarriger** [comment]
Hi @netomarchiori, thanks for posting!

I was able to reproduce the issue and have [updated](https://github.com/adriancarriger/angularfire2-offline/commit/0ea132962927978aaad670bf7dbc8112f1b585c8) the example to avoid the error. It looks like angularfire2 at version 4.0.0-rc.2 resulted in type erros but version 4.0.0-rc.0 works weel so I pinned the version.

## Steps to test change

Following these steps should now no longer produce the type errors you mentioned:

* `git clone https://github.com/adriancarriger/angularfire2-offline.git issue-62`
* `cd issue-62/examples/ionic`
* `npm install`
* `npm run ionic:serve`

Let me know if you have any questions. Thanks! 👍

**Comment by netomarchiori** [comment]
spot on! worked as expected! thanks @adriancarriger
