### ISSUE TITLE
Cannot find module 'angularfire2/interfaces'.

### ISSUE THREAD

**Issue by matheus-fatguys** [adriancarriger/angularfire2-offline#63]
I`m trying to add offline capabilities to my ionic application using angularfire2-offline, but I get the folowing error when I run ionic serve?

Typescript Error
Cannot find module 'angularfire2/interfaces'.
```
node_modules/angularfire2-offline/database/database.d.ts
import { FirebaseListFactoryOpts, FirebaseObjectFactoryOpts } from 'angularfire2/interfaces';

node_modules/angularfire2-offline/database/interfaces.d.ts
import { FirebaseListFactoryOpts } from 'angularfire2/interfaces';
node_modules/angularfire2-offline/database/list/afo-list-observable.d.ts
node_modules/angularfire2-offline/database/list/emulate-query.d.ts

```
My packacge.json:
"angularfire2": "^4.0.0-rc.2",
"angularfire2-offline": "^4.2.4",
"firebase": "^4.3.0",
"ionic-angular": "3.6.0",

I've already tryed to remove dependencies and adding them agein, but the error persists

I appreciate your help

**Comment by adriancarriger** [comment]
Hi @matheus-fatguys, if you set angularfire2 from `^4.0.0-rc.2` to `4.0.0-rc.0` it should work. 👍

**Comment by matheus-fatguys** [comment]
Thank you! I've done that and now i works.
Thank you.
