### ISSUE TITLE
ng build --prod works, ng build --prod --aot does not work

### ISSUE THREAD

**Issue by stefanaerts** [adriancarriger/angularfire2-offline#7]
It works nice for me without aot,but when i do ahead of time compilation it does not create the localforage indexed db database.

![image](https://cloud.githubusercontent.com/assets/3684599/23340848/a498288c-fc3d-11e6-822e-195b84f4a2cf.png)

**Comment by adriancarriger** [comment]
Thanks for the bug report! There should be a fix available in the next week.

**Comment by adriancarriger** [comment]
The latest version `2.0.1` should now work with AOT. Let me know if you experience any issues. Thanks!
