### ISSUE TITLE
Please add angularfire2 5

### ISSUE THREAD

**Issue by chris-eduardo** [adriancarriger/angularfire2-offline#76]

**Comment by H-beba** [comment]
yes please

**Comment by erikagtierrez** [comment]
YES

**Comment by JaneDawson** [comment]
any news / plan on this?

**Comment by JaneDawson** [comment]
Hi @adriancarriger: Can you please clarify, if you're planning on updating angularfire2-offline for AngularFire 5.0?
I love this plugin and, hence, it is the only thing that currently stops me from upgrading to the current version of AngularFire... Would be great to know, if any update is planned, or if we have to look for another offline solution...
Thank you! And thank you for this plugin!!

**Comment by martinkronstad** [comment]
Me too, I am stuck at Angular 4 because of this ...

**Comment by adriancarriger** [comment]
Closing in favor of issue #89
