### ISSUE TITLE
UI doesn´t work when you use trought providers and tab on ionic2

### ISSUE THREAD

**Issue by seedgabo** [adriancarriger/angularfire2-offline#8]
`import { Injectable,NgZone } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';
import { AngularFire, FirebaseListObservable } from 'angularfire2';
import {
    AngularFireOffline,
    AfoListObservable,
    AfoObjectObservable } from 'angularfire2-offline';

    @Injectable()
    export class Api {
        items: AfoListObservable<any>;
        workers:AfoListObservable<any>;
        vales: AfoListObservable<any>;
        constructor(public http: Http,public af: AngularFireOffline, public zone:NgZone) {
            this.zone.run(()=>{

                this.items = af.database.list('/items',{
                    query: {
                        limitToLast: 10,
                        orderByKey: true
                    }
                });

                this.workers = af.database.list('/workers');

                this.vales = af.database.list('/vales');
            })
        }

    }`

**Comment by adriancarriger** [comment]
Thanks for posting an issue. I had a few questions:

- Are you using version 2.0.2 of angularfire2-offline?
- What do you mean by "trought providers"?
- Is your issue affected by/related to using a query?
- Is the issue only present when you are using tabs?
- Can you show the Html template you're using?

**Comment by giorgiopiatti** [comment]
@seedgabo I've had a similar issue, for me this work fine:

My dbService:
```
import {Injectable} from "@angular/core";
import { AngularFireOffline, AfoListObservable, AfoObjectObservable } from 'angularfire2-offline';

@Injectable()
export class DbService {
  protected db: any;
  public dbData: AfoListObservable<any[]>;
  constructor(afo: AngularFireOffline) {
    this.db = afo.database;
}
initialize(){
  this.dbData = this.db.list('/items');
}
}
```

And because I want that the app work offline immediately as it starts I initialize the the observable in my app.component.ts.

In my page.ts
```
import { Component } from '@angular/core';
import { DbService } from '../../providers/db-service';
import {AfoListObservable} from 'angularfire2-offline';
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage{
  data: AfoListObservable<any[]>;
  constructor(
    private dbService: DbService) {
    this.data = this.dbService.dbData;
    console.log(this.data);
  }

  ionViewDidLoad(){
    this.dbService.initialize(); //If you don't call this it doesn't work
  }
}
```
Note that I recall the initialize function also in my page. By the way this works fine in a normal page and also in a tab page.

Ionic info
_Ionic Framework: 2.0.0
Ionic Native: 2.4.1
Ionic App Scripts: 1.1.3
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 7.4.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36_

**Comment by adriancarriger** [comment]
Before v2.0.3 I had an issue with switching tabs. Try updating to see if the issue is still present. Thanks!

**Comment by adriancarriger** [comment]
Haven't heard back in a while so I'm closing this. Feel free to comment if you can provide more info. Thanks!
