### ISSUE TITLE
Error angularfire2-offline

### ISSUE THREAD

**Issue by SHEMOLOPZ** [adriancarriger/angularfire2-offline#85]
versiones
angularfire2: "^5.0.0-rc.5-next",
angularfire2-offline: "4.2.5",
firebase: "4.8.0",

ionic info

cli packages: (C:\Users\USER\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v7.10.1
    npm  : 5.6.0
    OS   : Windows 10

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

ionic cordova build android => OK
ionic cordova emulate android -l -s -c  => ok 

Cuando voy a utilizar los componentes de AngularFire2 Offline siguiendo la referencia de 

https://github.com/adriancarriger/angularfire2-offline

me genera un error en el emulador de android 

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'toString' of undefined

mi código es el siguiente

import { AfoListObservable, AfoObjectObservable, 
             AngularFireOfflineDatabase } from 'angularfire2-offline/database';

public tasks: AfoListObservable<any[]>;
public dbUser: AfoObjectObservable<any>;

    constructor(
        public events: Events,
        private afoDatabase: AngularFireOfflineDatabase) { 
       //llamar  función offline
       initService();
    }

    initService(id: string) {
       //en el momento que llega a este punto se rompe y sale el error antes mensionado
        this.info = this.afoDatabase.object('/info');
        this.tasks = this.afoDatabase.list('/Tasks);
}

agradezco la ayuda.

**Comment by adriancarriger** [comment]
Closing in favor of issue #89
