### ISSUE TITLE
how to implement ion-searchbar filter item with AfoListObservable ?

### ISSUE THREAD

**Issue by m-saifuddin** [adriancarriger/angularfire2-offline#88]
I am trying to implement ion-searchbar with a filter over AfoListObservable which prompting below compile time error.

[ts]
Type 'Observable<any[]>' is not assignable to type 'AfoListObservable<any[]>'.
  Property 'internalListObservable' is missing in type 'Observable<any[]>'.

appreciated for your input.

**Comment by adriancarriger** [comment]
Hi @m-saifuddin it doesn't sound like this is related to this repo. I would [create a question at StackOverflow](https://stackoverflow.com/questions/ask).
